language: node_js
sudo: false
cache:
  directories:
    - node_modules
node_js:
  - "node"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version v1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add babel-cli
